### ISSUE TITLE
ConcurrentModificationException in shouldNotStartWith while running tests

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.ghlint#187]
### Version

dev 4095d9890d10be081ea304a4613855e728fac2e1

### Reproduction steps

Run DuplicateStepIdRule many times

### Expected behavior

Just works, always.

### Actual behavior

```

java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:786)
	at java.base/java.util.HashMap.putMapEntries(HashMap.java:511)
	at java.base/java.util.LinkedHashMap.<init>(LinkedHashMap.java:385)
	at kotlin.collections.MapsKt__MapsKt.toMutableMap(Maps.kt:627)
	at kotlin.collections.MapsKt__MapsKt.toMap(Maps.kt:618)
	at io.kotest.assertions.print.Printers.all(Printers.kt:52)
	at io.kotest.assertions.print.PrintKt.commonPrintFor(Print.kt:73)
	at io.kotest.assertions.print.PrintKt.printFor(Print.kt:62)
	at io.kotest.assertions.print.PrintKt.print(Print.kt:48)
	at io.kotest.matchers.string.StartKt$startWith$1.invoke(start.kt:24)
	at io.kotest.matchers.string.StartKt$startWith$1.invoke(start.kt:21)
	at io.kotest.matchers.MatcherKt$neverNullMatcher$$inlined$invoke$1.test(Matcher.kt:188)
	at io.kotest.matchers.Matcher$DefaultImpls$invert$$inlined$invoke$1.test(Matcher.kt:188)
	at io.kotest.matchers.NeverNullMatcher.test(Matcher.kt:76)
	at io.kotest.matchers.ShouldKt.invokeMatcher(should.kt:38)
	at io.kotest.matchers.ShouldKt.should(should.kt:33)
	at io.kotest.matchers.ShouldKt.shouldNot(should.kt:66)
	at io.kotest.matchers.string.StartKt.shouldNotStartWith(start.kt:17)
	at net.twisterrob.ghlint.testing.TestKt.testCompliantExamples$lambda$16$lambda$15(test.kt:130)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

### Additional Context

Very likely since https://github.com/TWiStErRob/net.twisterrob.ghlint/pull/183

**Comment by TWiStErRob** [comment]
Another instance of this:

[test.zip](https://github.com/TWiStErRob/net.twisterrob.ghlint/files/15008780/test.zip)
